### ISSUE TITLE
Civil War Attrition bug?

### ISSUE THREAD

**Issue by MrSkinny** [sellmerfud/awakening#6]
I think there's an issue with resolution timing in the Civil War Attrition phase.  See below scenario output.  Syria started the round with 4 Cells and 2 Militia + 1 Advisor.

```
Civil War Attrition
----------------------------------------------------
Add one militia to Syria due to presence of Advisors
Syria:
Jihadist die roll: 2
The Jihadist inflicts 1 hit on the US
US die roll : 3
The US inflicts 0 hits on the Jihadist
Remove 1 militia from Syria to the track
```

At beginning of phase, a new Militia is added so total should be 3.  US die roll is 3 so a hit should be inflicted on Jihadist, but it resolves 0 hits.  I'm not sure if this is because the Jihadist attack resolved first, caused the US hit, leaving the US at a value of 2 for its roll in error?

**Comment by MrSkinny** [comment]
Hmm, looking at this line:
https://github.com/sellmerfud/awakening/blob/master/src/main/scala/awakening/LabyrinthAwakening.scala#L3175

It seems correct in that it properly adds a militia to the country state and then resolves hits. Not sure what I'm missing...

**Comment by MrSkinny** [comment]
https://github.com/sellmerfud/awakening/blob/master/src/main/scala/awakening/LabyrinthAwakening.scala#L3184

Is `m.totalTroopsAndMilitia` a calculated prop?  I'm not sure if it's updated after `game.updateCountry` is invoked, which is where the militia gets added.

**Comment by sellmerfud** [comment]
The problem is that the list of countries in Civil War is not reevaluated after adding the militia for Advisors.

All of the data structures are immutable.   I have calculated the 'civilWars' variable as first line of the civilWarAttrition function, but then later I add a militia to Syria due to the presence of the Advisors.

When iterating through the list of countries in CivilWar, we still have the 'old' copy of Syria from before the militia was added.

I changed the 'val' declaration to a 'def' so that we now reevaluate the civil war countries each time we need to use them to ensure we get the latest copy of the data.

Thanks for reporting the problem.  I have check in a fix.  Version 3.3 is now available.
